### ISSUE TITLE
Unable to open a file in my locustfile.py

### ISSUE THREAD

**Issue by tvhtu** [SvenskaSpel/locust-swarm#18]
Hi, in my locustfile.py, I need to open a json file and I use
`with open(data.json) as f:`

I already put the file in the same folder with the locust file, however it returned an error that:

> ERROR/locust.user.users: [Errno 2] No such file or directory: '/data.json'
 Traceback (most recent call last):
   File "/home/name/.local/lib/python3.10/site-packages/locust/user/users.py", line 148, in run
     self.on_start()
   File "/tmp/locustfile.py", line 26, in on_start
     with open('/data.json') as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/data.json'
 
 > Traceback (most recent call last):
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
   File "/home/name/.local/lib/python3.10/site-packages/locust/user/users.py", line 186, in run_user
     user.run()
   File "/home/name/.local/lib/python3.10/site-packages/locust/user/users.py", line 148, in run
     self.on_start()
   File "/tmp/locustfile.py", line 26, in on_start
     with open('/data.json') as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/data.json'
 <Greenlet at 0x7f258ef8c400: run_user(<locustfile.MyUser object at 0x7f258ee15480>)> failed with FileNotFoundError`

I tried with directory path like `with open(/home/name/locust-project/data.json) as f:` but it still does not work. Running with locust not swarm is fine

**Comment by cyberw** [comment]
Seems the problem is that the file is only on master and not on workers? Either copy it manually or add `--extra-files data.json` to make swarm upload it on each run.

**Comment by tvhtu** [comment]
It worked! Thanks for your help
