### ISSUE TITLE
Waiting for workers to be ready error

### ISSUE THREAD

**Issue by ludeknovy** [SvenskaSpel/locust-swarm#7]
Lets say I have a VM with 30 CPU, so I want to run 30 workers on it.

When I run:

`swarm --loadgen-list server.domain --processes-per-loadgen 30 -f my_test.py -u 5000 -r 50`

it returns:
```
 returned non-zero exit status 255.
```

with trace:
```
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/swarm", line 395, in <module>
    check_proc_running(proc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/swarm", line 139, in check_proc_running
    raise subprocess.CalledProcessError(retcode, process.args)
```

The last log before the error is:
```
: Waiting for workers to be ready, 12 of 30 connected
```

**Comment by cyberw** [comment]
Please post or attach the full output, and run it with `-L debug` for more verbose output

**Comment by ludeknovy** [comment]
Ok, I solved it by adding `time.sleep(0.2)` on line 261 - `start_worker_process` method.

**Comment by ludeknovy** [comment]
Run it with the `-L debug`, 

```
[2021-05-02 21:33:36,430] Ludek-MacBook-Pro.local/INFO/locust.runners: Client 'my-server_b9a56e1603ae4f77bf7c174a3b774920' reported as ready. Currently 30 clients ready to swarm.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/swarm", line 396, in <module>
    check_proc_running(proc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/swarm", line 139, in check_proc_running
    raise subprocess.CalledProcessError(retcode, process.args)
subprocess.CalledProcessError: Command 'ssh -q my.server ' LOCUST_RUN_ID="2021-05-02T19:33:34.153083+00:00" PYTHONUNBUFFERED=1 locust --worker --master-port 5557 --headless -f file.py -u 10000 -r 50 & read; kill -9 $! '' returned non-zero exit status 255.

[swarm:167] cleanup started
```

the starting command is:
```
 swarm --loadgen-list my-server --processes-per-loadgen 38 --loadgens 1 -f file.py -u 10000 -r 50 -L debug
 ```

**Comment by cyberw** [comment]
Perhaps your server refuses the ssh connection? I'm not 100% sure what exit status 255 means, but it seems that is what it means https://stackoverflow.com/a/14885975/1591921

Perhaps there is a setting for sshd limiting the number of total ssh connections, or number of *new* connections per unit of time. If you want to investigate further then check your sshd logs.
